"""
Ejemplos de estructura alternativa.
- Uso de GOTO
- Alternativa simple -> if ...
- Alternativa doble -> if ... else ...
- Alternativa múltiple -> if ... elif ... / match_opc: case 1: ... case 2: ... (cualquier caso) _ : ...
"""
